#!/usr/bin/env bash

# Telepresence wrapper
# This version is symlinkable into your PATH, but you'll need to run `brew install coreutils` if running on macOS

exec docker-compose -f "$(dirname "$(readlink -f "$0")")/docker-compose.yml" run --rm telepresence-cli "$@"
